# Sidebar navigation

- label: 'Introdução'
  link: '/'
- label: Registros
  items:
    - label: 'Empresas e pessoas'
      link: '/register/person'
    - label: 'Tipo de empresa'
      link: '/register/types'
    - label: 'Endereços'
      link: '/register/addresses'
- label: Desenvolvimento
  items:
    - label: Api
      link: /dev/api
    - label: Autenticação
      link: /dev/auth
    - label: Sistema
      link: https://register.thalamus.digital/
    - label: Swagger
      link: https://register.thalamus.digital/swagger
    - label: Github
      link: https://github.com/thalamusfiles/register