version: "3.2"
services:
  register_db:
    container_name: register_postgres
    image: postgres:15-alpine
    shm_size: 1g
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - TZ=GMT
    volumes:
      - type: bind
        source: "../tmp/${DATABASE_LOCAL_FOLDER}"
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - register_backend-net
    ports:
      - ${DATABASE_PORT}:5001
    command: -p 5001

  register_backend:
    container_name: register_backend_server
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      SYSTEM_PORT: ${SYSTEM_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
    volumes:
      - "../:/var/www/app"
      - "/var/www/app/node_modules"
    networks:
      - docker_iam_backend-net
      - register_backend-net
    depends_on:
      - register_db
    ports:
      - ${SYSTEM_PORT}:3000
    command: 
      ${COMMAND_START}

networks:
  docker_iam_backend-net:
    external: true
  register_backend-net:
    driver: bridge
