export type RoutesName =
  // PUBLIC
  | 'login'
  | 'logout'
  | 'home_public'
  | 'persons'
  | 'person_legal'
  | 'person_legal_view'
  | 'person_partner'
  | 'contact'
  | 'types'
  | 'addresses'
  | 'addresses_zipcode'
  | 'rel_estab'
  | 'rel_estab_tt_month_state'
  | 'rel_estab_tt_month_state_history'
  | 'rel_type'
  | 'rel_type_tt_nature'
  | 'rel_type_tt_activity';
